### PR TITLE
Even more better Russian parties

### PR DESCRIPTION
**Pull request by VictorWeikum**
All Russian parties that has ever been in State Duma. I think I'm gonna stop now, 'cause there is about 150 parties in modern Russia (mostly microparties), maybe even more.

NOTE: All parties has been given authentic start and end dates, including the Communist party of Russia (not Soviet Union)! It is probably wise to give some parties with earlier start dates the 1836 start date until the Russian Federation will be created as a separate country from the Soviet Union in the game.

### CODE REVIEW

**Comment by VictorWeikum** [comment]
It contains problems with policies, I'm working on it

**Comment by VictorWeikum** [comment]
I don't know why, but parties with interventionism and anti_military policies are getting noissue is their policies

**Comment by simsulla** [comment]
The text.csv should be iso8859-15 encoded (Victoria 2 requires this). The latest text.csv in the repo is messed up. Could you please take the text.csv from 0.9.908 release, and add the Russian parties keeping the iso8859-15 encoding. Or if this is difficult move the party_conservative_0_RUS..... entries to a seprate csv file in the localisation folder named;
parties.csv

**Comment by VictorWeikum** [comment]
I runned the game without any problems, I edited and saved it in Excel 2016, the encoding shouldn't have changed. I resaved it in Latin-9 (iso8859-15)

**Comment by VictorWeikum** [comment]
Oh, wait, I took 1.0.0 version

**Comment by VictorWeikum** [comment]
Everything should be allright with text.csv now

**Comment by simsulla** [comment]
Thanks :+1:

**Comment by VictorWeikum** [comment]
What do you mean? Everything works well on my side, plus I did save it in iso8859-15 (though it doesn't make any difference).

**Comment by VictorWeikum** [comment]
I understood now, it's because of github and/or internet browser, it changes encoding when I copy the contents of csv to it. Is there any civilized way to download big files on github?

**Comment by simsulla** [comment]
Just cone (checkout) the nwomod repo. Edit the text.csv (or from now on
nwo_parties.csv) in notepadd++ seting the encoding to ANSI. That is it.

**Pull request merged**
