### PR TITLE
Democratic Russia -> EU

### PR DESCRIPTION
**Pull request by VictorWeikum**
Should be able to join if it is a democracy (was in reality in 1993-2000).

### CODE REVIEW

**Comment by simsulla** [comment]
Russia is democratic today, but far from joining the EU. Some additional criteria is needed.

**Comment by VictorWeikum** [comment]
Today Russia is democratic only in documents, it's a de facto presidential dictatorship with populists in power. The problem is Victoria II does not have rigged elections and massive propoganda mechanics (for a whole nation, there are modifiers for provinces, but they're not enough). I could make more events as a continuation of Khodorkovsky arrest event.

**Comment by simsulla** [comment]
That is a political statement. For NWO as it plays in our time it has to walk a carefully balanced way in the political landscape - giving room for all sides. As of 1.05 (at the time of writing this, the current release) I have tired to remove the label "dictatorship" for all regime types except Presidential Dictatorship - which correlates to a military junta. 
By ideology they are 
communist - People's Republic
populists - Republic (nationalist - Republic of)
Democracy and Parliamentary Democracy (hms_government) correlates to "Liberal" (or Western as the CPC calls it) Democracy. To change Russia into a "Republic", I need to read up on the Russian elections.

**Comment by VictorWeikum** [comment]
Russia has been a democracy in the 90s, but nobody was ready to protect it. People was always very apolitical. This is why it turned into what it is now - rule of people from special agencies and forces. Not a military junta, but somewhat alike.

**Comment by VictorWeikum** [comment]
I suggest creating corruption mechanics for such young democracies as post-Soviet countries through series of events and national flags

**Comment by simsulla** [comment]
Ok, we need a "Putins Russia" #444 event or decision that transform Russia in to a Republic. Added it.
Democratic Russia
image

Republic Russia
image

**Comment by VictorWeikum** [comment]
lol, by national flags i meant country_flag and country_modifier
but they actually did modify the national flag :D

**Pull request merged**
