### PR TITLE
19xx Crimean events

### PR DESCRIPTION
**Pull request by VictorWeikum**
I'm sorry, but could you please check the syntaxis? I checked everything twice, but I still could make some mistakes cause I'm new to vic2 coding. If I did, show them to me please.

### CODE REVIEW

**Comment by simsulla** [comment]
Nice work @VictorWeikum  :+1: 
A couple small things when adding events;
1. I try and organize events by country. So in case of Crime, please use Ukraine.tx (or Russia:) ). 
2. From ukraine.txt. use the next available event id from that file. **id = 1014206**
3. Localization, add the localization to nwo_events.csv. Else the Vic2validator gives lots of warnings.
For example; `title = "Belovezha Accords. Crimean question"` would become `title = EVT_1014206_NAME`
And in nwo_events.csv: EVT_1014206_NAME;Belovezha Accords. Crimean question;;;;;;;;;;X
and so on.
4. Use the Vic2Validator to check your events. For example some are missing picture =...

**Comment by yf22** [comment]
Pictures are not of necessity as the game will use a defult one if it is not defined in the event,though it may looks strange.

**Comment by simsulla** [comment]
Yes, that is true. But having a event related picture is nice for the player of the mod, and not having a picture gives a vic2Validator gives an error.

**Comment by VictorWeikum** [comment]
Actually I made Crimea.txt, because Crimea is a country by itself, and it changed owner twice during the 1946-2016 period (from RSFSR to UkrSSR in 1954 and from modern Ukraine to modern RF in 2014, both times contoversially). Is it okay?

**Comment by simsulla** [comment]
Yes, that is fine to have it in crimea.txt. But the changes you want to pull into the mode gives Victoria2 Validator errors. Changes you want to pull into the mod should give no errors. v1.13.3: https://www.dropbox.com/s/sailacvak1u96z0/Audax.Validator v1.13.3.zip?dl=0

image

**Comment by simsulla** [comment]
Fixed lots of errors in the merge... :-1: 
Hence forth merge requests that generate Validator errors will be rejected (unless the validator error is incorrect).

**Pull request merged**
