### PR TITLE
EAU and EU enhancement

### PR DESCRIPTION
**Pull request by VictorWeikum**
1. Presidential, nationalist and populist dictatorships can join EAU
2. any_neighbour_country replaced with any_country (Romania, Bulgaria, Armenia are real-life examples)
3. Allowed change regime event to democracy for all dictatorships. Allowed great power presidential dictatorship change regime event against democracies.

### CODE REVIEW

**Comment by VictorWeikum** [comment]
How do I create a .tga picture? It is a format of 3d printer models and does not open in my picture editor.

**Comment by VictorWeikum** [comment]
Note: probably must add year=1991 to potential in EAU, or a list of all possible post-Soviet countries + Mongolia

**Comment by VictorWeikum** [comment]
Mistake in a description
	Khodorkovsky arrest event …
Allows to switch to presidential_dictatorship of course

**Comment by simsulla** [comment]
I have merged the events - with some corrections - please use the Victoria
2 Validator to ensure that there are no typos.

**Pull request merged**
